################################################################################
################################################################################
##                                                                            ##
##                    SaferWater Configuration for Bukkit                     ##
##                                                                            ##
## SOURCE CODE: https://github.com/bspfsystems/SaferWater/                    ##
## BUGS / ISSUES: https://github.com/bspfsystems/SaferWater/issues/           ##
##                                                                            ##
## New configuration items will not be added to this file automatically. You  ##
## can obtain an update version of the default config.yml file from           ##
## https://bspfsystems.org/config-files/saferwater/bukkit/                    ##
##                                                                            ##
## This file may also be called "saferwater.yml". If both "saferwater.yml"    ##
## and "config.yml" are present in this plugin's configuration directory, the ##
## "saferwater.yml" file will be preferred over the "config.yml" file.        ##
##                                                                            ##
## For more information on configuring SaferWater, including each individual  ##
## configuration option in this file, please see the configuration            ##
## documentation at https://bspfsystems.org/config-docs/saferwater/           ##
##                                                                            ##
################################################################################
################################################################################

################################################################################
#                           General Plugin Settings                            #
################################################################################

# The logging level for the plugin logger.
# The default value is "INFO".
logging_level: "INFO"

# The blacklist of mobs that will not be allowed to spawn in water.
# By default, no mobs are restricted from spawning.
# Example configuration:
# 
# disallowed_mobs:
#   - "Drowned"
#   - "Guardian"
disallowed_mobs:
